//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothéque.Data_Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprinte
    {
        public int Id { get; set; }
        public Nullable<int> Id_RSV { get; set; }
        public int Nbr_Days { get; set; }
        public System.DateTime Date_Emprinte { get; set; }
        public Nullable<System.DateTime> Date_Retourne { get; set; }
    
        public virtual Reserve Reserve { get; set; }
    }
}
