//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothéque.Data_Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filière
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filière()
        {
            this.Groupes = new HashSet<Groupe>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_SCT { get; set; }
        public string Nom { get; set; }
    
        public virtual Secteur Secteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groupe> Groupes { get; set; }
    }
}
